version: 2
jobs:
  deploy:
    docker:
      - image: devillex/docker-firebase:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn
      - run:
          name: build react
          command: yarn build
      - run:
          name: firebase setting
          command: firebase use deploytest-5e1c6 --token=$FIREBASE_DEPLOY_TOKEN
      - run:
          name: deploy firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master